application:
 title: May the force be with you
 version: 0.0.1

spring:
 profiles:
    active: test
 datasource:
   url: jdbc:mysql://localhost:3306/toby_spring?characterEncoding=UTF-8&serverTimezone=UTC
   username: root
   password: 0389
   driver-class-name: com.mysql.cj.jdbc.Driver

# profiles:
#    active: test
# datasource:
#   url: jdbc:h2:mem:test
#   username: sa
#   password:
#   driver-class-name: org.h2.Driver