application:
 title: May the force be with you
 version: 0.0.1

spring:
 profiles:
    active: test
 datasource:
   url: jdbc:h2:mem:test
   username: sa
   password:
   driver-class-name: org.h2.Driver